services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    depends_on:
      - mongo

  ui:
    build:
      context: ui
      dockerfile: Dockerfile
      
    volumes:
      - ./ui/applications/web3-app/src:/app/applications/web3-app/src:ro
      - ./ui/applications/web3-app/next.config.mjs:/app/applications/web3-app/next.config.mjs:ro
      - ./ui/applications/web3-app/tsconfig.json:/app/applications/web3-app/tsconfig.json:ro
      - ./ui/applications/web3-app/package.json:/app/applications/web3-app/package.json:ro
    
    ports:
      - "3001:3000"
    
    environment:
      - NODE_ENV=development
      # - NEXT_PUBLIC_WEB3_AUTH_ENDPOINT=
      
    depends_on:
      - api

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: